<Project Sdk="Godot.NET.Sdk/4.6.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>NeonArena</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Arch" Version="2.1.0" />
    <PackageReference Include="Arch.System" Version="1.1.0" />
  </ItemGroup>
</Project>